name: nrss

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - cyrsoxs
  - cupy-cuda12x
  - xarray
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - h5py
  
