name: nrss

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - sphinx==7.1.2
  - pydata-sphinx-theme==0.13.3
  - sphinx-design
  - xarray
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - h5py
