name: nrss

channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - cyrsoxs
  - sphinx
  - pydata-sphinx-theme==0.13.3
  - sphinx-design
  - xarray
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - h5py
